name: Renovate

on:
  schedule:
    - cron: "0 8 * * 1"
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: renovatebot/github-action@693b9ef15eec82123529a37c782242f091365961 # v46.1.14
        with:
          configurationFile: renovate.json
        env:
          RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN }}
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          GIT_AUTHOR_NAME: micschro
          GIT_AUTHOR_EMAIL: micschro@mailbox.org
          GIT_COMMITTER_NAME: micschro
          GIT_COMMITTER_EMAIL: micschro@mailbox.org
